title: Email required?
main-page-title: The problem
description: >-
  You might be sending random people your users' data
baseurl: ""
url: "https://email-required.com"
github_username:  PrinsFrank
theme: minima
plugins:
  - jekyll-feed
